version: "3.9"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  groupd:
    build: .
    depends_on:
      - redis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./secrets:/app/secrets